/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    
        

    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IFLOGO = new javax.swing.JLabel();
        BEMVINDO = new javax.swing.JLabel();
        IFITNESS = new javax.swing.JLabel();
        jTextFieldUsuário = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        SENHA = new javax.swing.JLabel();
        USUÁRIO = new javax.swing.JLabel();
        SAIR = new javax.swing.JButton();
        ACESSO = new javax.swing.JButton();
        IMAGEM = new javax.swing.JLabel();
        imagemteste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        IFLOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AAAAAAAAAAAAAAA.png"))); // NOI18N
        IFLOGO.setText("jLabel1");
        getContentPane().add(IFLOGO);
        IFLOGO.setBounds(720, 0, 250, 190);

        BEMVINDO.setFont(new java.awt.Font("Orator Std", 0, 48)); // NOI18N
        BEMVINDO.setText("BEM VINDO AO ");
        getContentPane().add(BEMVINDO);
        BEMVINDO.setBounds(100, 40, 410, 100);

        IFITNESS.setFont(new java.awt.Font("Orator Std", 0, 48)); // NOI18N
        IFITNESS.setText("IFFITNESS");
        getContentPane().add(IFITNESS);
        IFITNESS.setBounds(540, 50, 390, 90);

        jTextFieldUsuário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuárioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuário);
        jTextFieldUsuário.setBounds(540, 160, 250, 30);

        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(540, 200, 250, 30);

        SENHA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SENHA.setText("Senha:");
        getContentPane().add(SENHA);
        SENHA.setBounds(400, 200, 140, 20);

        USUÁRIO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        USUÁRIO.setText("Usuário:");
        getContentPane().add(USUÁRIO);
        USUÁRIO.setBounds(400, 170, 110, 22);

        SAIR.setText("Sair");
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });
        getContentPane().add(SAIR);
        SAIR.setBounds(620, 530, 120, 40);

        ACESSO.setText("Acesso");
        ACESSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACESSOActionPerformed(evt);
            }
        });
        getContentPane().add(ACESSO);
        ACESSO.setBounds(290, 530, 130, 40);

        IMAGEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fitness-super-store-uk.jpg"))); // NOI18N
        getContentPane().add(IMAGEM);
        IMAGEM.setBounds(0, 0, 992, 620);

        imagemteste.setText("jLabel1");
        getContentPane().add(imagemteste);
        imagemteste.setBounds(510, 80, 34, 14);

        setSize(new java.awt.Dimension(1008, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ACESSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACESSOActionPerformed
            TelaComecar tela = new TelaComecar();
    
    if (jTextFieldUsuário.getText().equals("professor") && jPasswordFieldSenha.getText().equals("ifal")){
    tela.setVisible(true);
    dispose();
    }else{
        JOptionPane.showMessageDialog(rootPane, "Senha ou Usuário incorretos!");
    }

            
    }//GEN-LAST:event_ACESSOActionPerformed

    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
      System.exit(0);
    dispose();
    }//GEN-LAST:event_SAIRActionPerformed

    private void jTextFieldUsuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuárioActionPerformed
     

    }//GEN-LAST:event_jTextFieldUsuárioActionPerformed

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACESSO;
    private javax.swing.JLabel BEMVINDO;
    private javax.swing.JLabel IFITNESS;
    private javax.swing.JLabel IFLOGO;
    private javax.swing.JLabel IMAGEM;
    private javax.swing.JButton SAIR;
    private javax.swing.JLabel SENHA;
    private javax.swing.JLabel USUÁRIO;
    private javax.swing.JLabel imagemteste;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuário;
    // End of variables declaration//GEN-END:variables
}
